version: "2"

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -k gevent -b 0.0.0.0:6015 pdb_vis.application:app
    environment:
      - PDB_VIS_SETTINGS=/usr/src/app/prd_settings.py
    ports:
      - "6015:6015"
    volumes:
      - "/mnt/chelonium:/mnt/cmbi4"
